export type Person = {
    id: string;
    name: string;
    userName: string;
    email: string;
    dueDate: string;
    amount: number;
    status: string;
    projectTitle: string;
};

export const defaultData = [
    {
        id: "62447",
        name: "Francis Sanford MD",
        userName: "George33",
        email: "Marya.Barrow@yahoo.com",
        dueDate: "2023-10-18T13:24:00.760Z",
        amount: 544,
        status: "Paid",
        projectTitle: "Website Redesign",
    },
    {
        id: "86740",
        name: "Lucia Kshlerin",
        userName: "Kenyon_Goldner56",
        email: "Mason_Davis4@yahoo.com",
        dueDate: "2023-07-18T01:06:16.095Z",
        amount: 560,
        status: "Pending",
        projectTitle: "Mobile App Development",
    },
    {
        id: "42548",
        name: "Byron Hoppe III",
        userName: "Walton.Hane98",
        email: "Jayda_Schill35@yahoo.com",
        dueDate: "2024-12-18T15:32:21.317Z",
        amount: 249,
        status: "Pending",
        projectTitle: "E-commerce Platform",
    },
    {
        id: "97024",
        name: "Camille Jenkins",
        userName: "Dalton_Von55",
        email: "Retha.Lehne47@hotmail.com",
        dueDate: "2024-06-30T19:06:03.018Z",
        amount: 255,
        status: "Draft",
        projectTitle: "CRM System",
    },
    {
        id: "14608",
        name: "Kelli Mitchell",
        userName: "Iva.Denesik",
        email: "Guise.Champ@hotmail.com",
        dueDate: "2025-07-24T18:45:02.179Z",
        amount: 329,
        status: "Paid",
        projectTitle: "Social Media Campaign",
    },
    {
        id: "95656",
        name: "Randall Kuhic",
        userName: "Henry_Quigley0",
        email: "Simeon93@yahoo.com",
        dueDate: "2023-11-02T00:20:47.253Z",
        amount: 402,
        status: "Paid",
        projectTitle: "Product Launch",
    },
    {
        id: "73151",
        name: "Jody Carroll",
        userName: "Lavon32",
        email: "Frieda_Renne@gmail.com",
        dueDate: "2024-01-03T02:53:29.596Z",
        amount: 977,
        status: "Overdue",
        projectTitle: "Market Analysis",
    },
    {
        id: "57931",
        name: "Jill Russel",
        userName: "Abdiel.Terry",
        email: "Cleora.Murra@hotmail.com",
        dueDate: "2025-01-23T08:52:39.081Z",
        amount: 736,
        status: "Paid",
        projectTitle: "Event Planning",
    },
    {
        id: "36515",
        name: "Genevieve Hammes",
        userName: "Kian_Huels",
        email: "Bernard63@yahoo.com",
        dueDate: "2024-07-29T18:18:19.193Z",
        amount: 755,
        status: "Draft",
        projectTitle: "Digital Marketing",
    },
    {
        id: "34893",
        name: "Alejandro Reichert",
        userName: "Timothy91",
        email: "Wava.Mulle47@gmail.com",
        dueDate: "2023-05-04T04:33:47.908Z",
        amount: 240,
        status: "Draft",
        projectTitle: "SEO Optimization",
    },
    {
        id: "66356",
        name: "Ricardo Kling",
        userName: "Celia.Shanahan86",
        email: "Gene73@yahoo.com",
        dueDate: "2025-04-16T11:49:15.276Z",
        amount: 852,
        status: "Overdue",
        projectTitle: "Content Creation",
    },
    {
        id: "81467",
        name: "Carl Bode",
        userName: "Pablo_Thompson",
        email: "Virgil.Skile@hotmail.com",
        dueDate: "2024-05-28T04:44:49.629Z",
        amount: 295,
        status: "Draft",
        projectTitle: "UI/UX Design",
    },
    {
        id: "14042",
        name: "Sherry Weber",
        userName: "Shane39",
        email: "Aidan22@hotmail.com",
        dueDate: "2025-11-30T00:34:34.822Z",
        amount: 318,
        status: "Paid",
        projectTitle: "Brand Strategy",
    },
    {
        id: "49825",
        name: "Erika O'Reilly",
        userName: "Hazle_Bednar95",
        email: "Ardith57@yahoo.com",
        dueDate: "2024-05-17T06:24:33.253Z",
        amount: 463,
        status: "Overdue",
        projectTitle: "Advertising Campaign",
    },
    {
        id: "81929",
        name: "Lillian Anderson",
        userName: "Cyrus_Hettinger",
        email: "Aletha_Watrs87@gmail.com",
        dueDate: "2023-12-29T04:41:54.007Z",
        amount: 196,
        status: "Pending",
        projectTitle: "Business Plan",
    },
    {
        id: "25086",
        name: "Connie Braun",
        userName: "Ramona99",
        email: "Mervin.Ruerford@hotmail.com",
        dueDate: "2024-12-27T21:39:17.142Z",
        amount: 384,
        status: "Draft",
        projectTitle: "Customer Survey",
    },
    {
        id: "79737",
        name: "Mattie Miller",
        userName: "Madison_MacGyver-Lesch52",
        email: "Bianka30@yahoo.com",
        dueDate: "2025-06-27T15:53:33.802Z",
        amount: 812,
        status: "Paid",
        projectTitle: "Training Program",
    },
    {
        id: "66747",
        name: "Shelley Lind-VonRueden",
        userName: "Issac_West",
        email: "Destini_Wiamson34@yahoo.com",
        dueDate: "2024-12-29T09:04:48.858Z",
        amount: 596,
        status: "Pending",
        projectTitle: "System Integration",
    },
    {
        id: "44937",
        name: "Manuel Langworth",
        userName: "Kelley71",
        email: "Philip.OKfe94@gmail.com",
        dueDate: "2025-12-20T09:41:31.402Z",
        amount: 545,
        status: "Pending",
        projectTitle: "Software Development",
    },
    {
        id: "11420",
        name: "Dr. Guillermo Huels Jr.",
        userName: "Linnie.Hane",
        email: "Ricky41@yahoo.com",
        dueDate: "2023-03-26T14:06:10.093Z",
        amount: 537,
        status: "Paid",
        projectTitle: "Data Analysis",
    },
];
